// <auto-generated />
using System;
using ClearRiskApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClearRiskApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ClearRiskApi.Models.AuditReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActivityRisk")
                        .HasColumnType("REAL");

                    b.Property<bool>("BlockchainLogged")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CodeTransparencyRisk")
                        .HasColumnType("REAL");

                    b.Property<string>("ContractAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double>("DistributionRisk")
                        .HasColumnType("REAL");

                    b.Property<double>("FinalScore")
                        .HasColumnType("REAL");

                    b.Property<double>("LiquidityRisk")
                        .HasColumnType("REAL");

                    b.Property<double>("OwnershipRisk")
                        .HasColumnType("REAL");

                    b.Property<string>("ReportHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionHash")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditReports");
                });
#pragma warning restore 612, 618
        }
    }
}
